[parity]
chain = "demo-spec.json"
base_path = "/tmp/parity0"

[network]
port = 30300

[rpc]
port = 8540
apis = ["all"]

[ui]
port = 8180

[account]
password = ["node.pwds"]

[mining]
engine_signer = "0x4b36dA8ce32F25F13A19B5d4b40d4e97fA45df5f"
reseal_on_txs = "none"
